import fs from 'node:fs';
import path from 'node:path';

/**
 * Catalog + typings file emission. Catalog files are written sorted,
 * 2-space indented, with a trailing newline — stable output, minimal
 * diffs, matches the server's canonical ordering.
 */

/** Sorted keys, 2-space indent, trailing newline. */
export function stableCatalogJson(catalog: Record<string, string>): string {
  const sorted: Record<string, string> = {};
  for (const k of Object.keys(catalog).sort()) sorted[k] = catalog[k]!;
  return `${JSON.stringify(sorted, null, 2)}\n`;
}

export function writeCatalog(file: string, catalog: Record<string, string>): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, stableCatalogJson(catalog), 'utf8');
}

export function readCatalog(file: string): Record<string, string> | null {
  if (!fs.existsSync(file)) return null;
  const raw = JSON.parse(fs.readFileSync(file, 'utf8')) as unknown;
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return null;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(raw)) {
    if (typeof v === 'string') out[k] = v;
  }
  return out;
}

export function writeJson(file: string, value: unknown): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

/**
 * Namespaced catalog key — mirror of backend/src/lib/catalog.ts:
 * 'default' keys stay bare, other namespaces are dotted.
 */
export function catalogKeyName(namespace: string, name: string): string {
  return namespace === 'default' ? name : `${namespace}.${name}`;
}

/**
 * Render `locavello.d.ts` — a `LocavelloKey` string-literal union of
 * every key name plus the declaration-merging hook that narrows
 * `@forjio/locavello-next`'s `t()` key parameter.
 *
 * `export type` keeps the file a module, so the `declare module` block
 * AUGMENTS the package types (interface merge) instead of shadowing
 * them as an ambient module.
 */
export function renderDts(keys: string[]): string {
  const sorted = [...new Set(keys)].sort();
  const union =
    sorted.length === 0
      ? 'export type LocavelloKey = string;\n'
      : `export type LocavelloKey =\n${sorted.map((k) => `  | ${JSON.stringify(k)}`).join('\n')};\n`;
  return [
    '// Generated by `locavello pull` — do not edit by hand.',
    '',
    union,
    "declare module '@forjio/locavello-next' {",
    '  interface RegisteredKeys {',
    '    keys: LocavelloKey;',
    '  }',
    '}',
    '',
  ].join('\n');
}
