// Every Locavello feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 47 feature routes of the Locavello API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** Mint `lv_live_…`. (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** Delete an api key (DELETE /api/v1/api-keys/{id}) */
  apiKeysDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/api-keys/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** List audit (GET /api/v1/audit) */
  auditList(input?: { "action"?: unknown; "actor"?: unknown; "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["action"] = all["action"]; delete all["action"];
    query["actor"] = all["actor"]; delete all["actor"];
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/audit`, query, undefined);
  }

  /** Create a checkout (POST /api/v1/billing/checkout) */
  billingCheckout(input: { "tier": "free" | "starter" | "pro" | "scale"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** List billing (GET /api/v1/billing) */
  billingList(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing`, {}, undefined);
  }

  /** Create a glossary (POST /api/v1/glossary) */
  glossaryCreate(input: { "term": string; "projectId"?: string; "locale"?: string; "translation"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/glossary`, query, all);
  }

  /** Delete a glossary (DELETE /api/v1/glossary/{id}) */
  glossaryDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/glossary/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List glossary (GET /api/v1/glossary) */
  glossaryList(input?: { "projectId"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["projectId"] = all["projectId"]; delete all["projectId"];
    return this.call("GET", `/api/v1/glossary`, query, undefined);
  }

  /** Update a glossary (PATCH /api/v1/glossary/{id}) */
  glossaryUpdate(id: string, input?: { "term"?: string; "projectId"?: string; "locale"?: string; "translation"?: string; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/glossary/${encodeURIComponent(id)}`, query, all);
  }

  /** Write a translation. (PUT /api/v1/keys/{keyId}/translations/{locale}) */
  keysTranslations(keyId: string, locale: string, input: { "value": string; "status"?: "machine" | "needs_review" | "approved"; "author"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/keys/${encodeURIComponent(keyId)}/translations/${encodeURIComponent(locale)}`, query, all);
  }

  /** Context metadata edits from the workbench. (PATCH /api/v1/keys/{keyId}) */
  keysUpdate(keyId: string, input?: { "description"?: string; "maxLength"?: number; "screenshotUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/keys/${encodeURIComponent(keyId)}`, query, all);
  }

  /** The CI gate report. (GET /api/v1/projects/{id}/check) */
  projectsCheck(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/check`, {}, undefined);
  }

  /** Queue a Mode B crawl of the project's siteUrl. (POST /api/v1/projects/{id}/crawl) */
  projectsCrawl(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/crawl`, {}, undefined);
  }

  /** Create a project (POST /api/v1/projects) */
  projectsCreate(input: { "slug": string; "name": string; "sourceLocale"?: string; "mode"?: "sdk" | "proxy"; "siteUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects`, query, all);
  }

  /** Locales a project (POST /api/v1/projects/{id}/locales) */
  projectsCreateLocales(id: string, input: { "tag": string; "fallback"?: string; "rtl"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/locales`, query, all);
  }

  /** Namespaces a project (POST /api/v1/projects/{id}/namespaces) */
  projectsCreateNamespaces(id: string, input: { "name": string; "reviewPolicy"?: "standard" | "gated"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/namespaces`, query, all);
  }

  /** Publish. (POST /api/v1/projects/{id}/releases) */
  projectsCreateReleases(id: string, input: { "locale": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/releases`, query, all);
  }

  /** Get a project (GET /api/v1/projects/{id}) */
  projectsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List jobs (GET /api/v1/projects/{id}/jobs) */
  projectsJobs(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/jobs`, {}, undefined);
  }

  /** Get a job (GET /api/v1/projects/jobs/{jobId}) */
  projectsJobs2(jobId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/jobs/${encodeURIComponent(jobId)}`, {}, undefined);
  }

  /** The workbench list. (GET /api/v1/projects/{id}/keys) */
  projectsKeys(id: string, input?: { "archived"?: unknown; "locale"?: unknown; "namespace"?: unknown; "q"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["archived"] = all["archived"]; delete all["archived"];
    query["locale"] = all["locale"]; delete all["locale"];
    query["namespace"] = all["namespace"]; delete all["namespace"];
    query["q"] = all["q"]; delete all["q"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/keys`, query, undefined);
  }

  /** List projects (GET /api/v1/projects) */
  projectsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/projects`, {}, undefined);
  }

  /** List locales (GET /api/v1/projects/{id}/locales) */
  projectsLocales(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/locales`, {}, undefined);
  }

  /** List pages (GET /api/v1/projects/{id}/pages) */
  projectsPages(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/pages`, {}, undefined);
  }

  /** The CI endpoint. (GET /api/v1/projects/{id}/pull) */
  projectsPull(id: string, input?: { "draft"?: unknown; "pseudo"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["draft"] = all["draft"]; delete all["draft"];
    query["pseudo"] = all["pseudo"]; delete all["pseudo"];
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/pull`, query, undefined);
  }

  /** List releases (GET /api/v1/projects/{id}/releases) */
  projectsReleases(id: string, input?: { "locale"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["locale"] = all["locale"]; delete all["locale"];
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/releases`, query, undefined);
  }

  /** The frozen catalog (Mode B serving + diffs read this). (GET /api/v1/projects/releases/{releaseId}) */
  projectsReleases2(releaseId: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/releases/${encodeURIComponent(releaseId)}`, {}, undefined);
  }

  /** Key-level diff between two releases. (GET /api/v1/projects/releases/{a}/diff/{b}) */
  projectsReleasesDiff(a: string, b: string): Promise<unknown> {
    return this.call("GET", `/api/v1/projects/releases/${encodeURIComponent(a)}/diff/${encodeURIComponent(b)}`, {}, undefined);
  }

  /** Everything machine-produced or flagged, with the key context the reviewer needs, oldest first. (GET /api/v1/projects/{id}/review-queue) */
  projectsReviewQueue(id: string, input?: { "locale"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["locale"] = all["locale"]; delete all["locale"];
    return this.call("GET", `/api/v1/projects/${encodeURIComponent(id)}/review-queue`, query, undefined);
  }

  /** The extract/push endpoint. (PUT /api/v1/projects/{id}/keys) */
  projectsSetKeys(id: string, input: { "keys": unknown[]; "prune"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/projects/${encodeURIComponent(id)}/keys`, query, all);
  }

  /** Queue a machine first pass for a locale. (POST /api/v1/projects/{id}/translate) */
  projectsTranslate(id: string, input: { "locale": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/projects/${encodeURIComponent(id)}/translate`, query, all);
  }

  /** Update a project (PATCH /api/v1/projects/{id}) */
  projectsUpdate(id: string, input?: { "name"?: string; "siteUrl"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/projects/${encodeURIComponent(id)}`, query, all);
  }

  /** Update a locale (PATCH /api/v1/projects/{id}/locales/{tag}) */
  projectsUpdateLocales(id: string, tag: string, input?: { "fallback"?: string; "rtl"?: boolean; "enabled"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/projects/${encodeURIComponent(id)}/locales/${encodeURIComponent(tag)}`, query, all);
  }

  /** Update a namespace (PATCH /api/v1/projects/{id}/namespaces/{name}) */
  projectsUpdateNamespaces(id: string, name: string, input: { "reviewPolicy": "standard" | "gated"; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/projects/${encodeURIComponent(id)}/namespaces/${encodeURIComponent(name)}`, query, all);
  }

  /** Create a preview (POST /api/v1/public/preview) */
  publicCreatePreview(input: { "url": string; "targetLocale"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/public/preview`, query, all);
  }

  /** Poll a preview. previewId is an unguessable ULID; returns {status: 'running'|'done'|'failed', pairs?} and finalizes the job row on the first terminal poll. (GET /api/v1/public/preview/{id}) */
  publicPreview(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/public/preview/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** What locavello.js consumes. (GET /api/v1/public/projects/{id}/catalog) */
  publicProjectsCatalog(id: string, input?: { "locale"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["locale"] = all["locale"]; delete all["locale"];
    return this.call("GET", `/api/v1/public/projects/${encodeURIComponent(id)}/catalog`, query, undefined);
  }

  /** Browse the whole memory, newest-first, cursor-paged. (GET /api/v1/tm) */
  tmList(input?: { "target"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["target"] = all["target"]; delete all["target"];
    return this.call("GET", `/api/v1/tm`, query, undefined);
  }

  /** The TM screen's cross-project search. (GET /api/v1/tm/search) */
  tmSearch(input?: { "q"?: unknown; "target"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    query["target"] = all["target"]; delete all["target"];
    return this.call("GET", `/api/v1/tm/search`, query, undefined);
  }

  /** Workbench + agent suggestions. (GET /api/v1/tm/suggest) */
  tmSuggest(input?: { "target"?: unknown; "text"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["target"] = all["target"]; delete all["target"];
    query["text"] = all["text"]; delete all["text"];
    return this.call("GET", `/api/v1/tm/suggest`, query, undefined);
  }

  /** Approve a translation (POST /api/v1/translations/{id}/approve) */
  translationsApprove(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/translations/${encodeURIComponent(id)}/approve`, {}, undefined);
  }

  /** Reject a translation (POST /api/v1/translations/{id}/reject) */
  translationsReject(id: string, input: { "reason": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/translations/${encodeURIComponent(id)}/reject`, query, all);
  }

  /** Create a webhook subscription (POST /api/v1/webhook-subscriptions) */
  webhookSubscriptionsCreate(input: { "url": string; "events"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhook-subscriptions`, query, all);
  }

  /** Delete a webhook subscription (DELETE /api/v1/webhook-subscriptions/{id}) */
  webhookSubscriptionsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhook-subscriptions/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List webhook subscriptions (GET /api/v1/webhook-subscriptions) */
  webhookSubscriptionsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhook-subscriptions`, {}, undefined);
  }

  /** Update a webhook subscription (PATCH /api/v1/webhook-subscriptions/{id}) */
  webhookSubscriptionsUpdate(id: string, input: { "active": boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhook-subscriptions/${encodeURIComponent(id)}`, query, all);
  }
}
