// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; aliases?: string[]; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "api-keys",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/api-keys",
    "summary": "Mint `lv_live_…`.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/api-keys/{id}",
    "summary": "Delete an api key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/api-keys",
    "summary": "List api keys",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "audit",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/audit",
    "summary": "List audit",
    "pathParams": [],
    "query": [
     {
      "name": "action",
      "kind": "string",
      "required": false
     },
     {
      "name": "actor",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "billing",
  "routes": [
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/billing/checkout",
    "summary": "Create a checkout",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "tier",
      "kind": "string",
      "required": true,
      "choices": [
       "free",
       "starter",
       "pro",
       "scale"
      ]
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/billing",
    "summary": "List billing",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "glossary",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/glossary",
    "summary": "Create a glossary",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "term",
      "kind": "string",
      "required": true
     },
     {
      "name": "projectId",
      "kind": "string",
      "required": false
     },
     {
      "name": "locale",
      "kind": "string",
      "required": false
     },
     {
      "name": "translation",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/glossary/{id}",
    "summary": "Delete a glossary",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/glossary",
    "summary": "List glossary",
    "pathParams": [],
    "query": [
     {
      "name": "projectId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/glossary/{id}",
    "summary": "Update a glossary",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "term",
      "kind": "string",
      "required": false
     },
     {
      "name": "projectId",
      "kind": "string",
      "required": false
     },
     {
      "name": "locale",
      "kind": "string",
      "required": false
     },
     {
      "name": "translation",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "keys",
  "routes": [
   {
    "name": "translations",
    "method": "PUT",
    "path": "/api/v1/keys/{keyId}/translations/{locale}",
    "summary": "Write a translation.",
    "pathParams": [
     "keyId",
     "locale"
    ],
    "query": [],
    "body": [
     {
      "name": "value",
      "kind": "string",
      "required": true
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "machine",
       "needs_review",
       "approved"
      ]
     },
     {
      "name": "author",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/keys/{keyId}",
    "summary": "Context metadata edits from the workbench.",
    "pathParams": [
     "keyId"
    ],
    "query": [],
    "body": [
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "maxLength",
      "kind": "number",
      "required": false
     },
     {
      "name": "screenshotUrl",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "projects",
  "routes": [
   {
    "name": "check",
    "method": "GET",
    "path": "/api/v1/projects/{id}/check",
    "summary": "The CI gate report.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "crawl",
    "method": "POST",
    "path": "/api/v1/projects/{id}/crawl",
    "summary": "Queue a Mode B crawl of the project's siteUrl.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/projects",
    "summary": "Create a project",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "slug",
      "kind": "string",
      "required": true
     },
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "sourceLocale",
      "kind": "string",
      "required": false
     },
     {
      "name": "mode",
      "kind": "string",
      "required": false,
      "choices": [
       "sdk",
       "proxy"
      ]
     },
     {
      "name": "siteUrl",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-locales",
    "method": "POST",
    "path": "/api/v1/projects/{id}/locales",
    "summary": "Locales a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "tag",
      "kind": "string",
      "required": true
     },
     {
      "name": "fallback",
      "kind": "string",
      "required": false
     },
     {
      "name": "rtl",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "create-namespaces",
    "method": "POST",
    "path": "/api/v1/projects/{id}/namespaces",
    "summary": "Namespaces a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "reviewPolicy",
      "kind": "string",
      "required": false,
      "choices": [
       "standard",
       "gated"
      ]
     }
    ]
   },
   {
    "name": "create-releases",
    "method": "POST",
    "path": "/api/v1/projects/{id}/releases",
    "summary": "Publish.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "locale",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/projects/{id}",
    "summary": "Get a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get-jobs",
    "method": "GET",
    "path": "/api/v1/projects/jobs/{jobId}",
    "summary": "Get a job",
    "pathParams": [
     "jobId"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "jobs-2"
    ]
   },
   {
    "name": "get-releases",
    "method": "GET",
    "path": "/api/v1/projects/releases/{releaseId}",
    "summary": "The frozen catalog (Mode B serving + diffs read this).",
    "pathParams": [
     "releaseId"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "releases-2"
    ]
   },
   {
    "name": "jobs",
    "method": "GET",
    "path": "/api/v1/projects/{id}/jobs",
    "summary": "List jobs",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "keys",
    "method": "GET",
    "path": "/api/v1/projects/{id}/keys",
    "summary": "The workbench list.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "archived",
      "kind": "string",
      "required": false
     },
     {
      "name": "locale",
      "kind": "string",
      "required": false
     },
     {
      "name": "namespace",
      "kind": "string",
      "required": false
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/projects",
    "summary": "List projects",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "locales",
    "method": "GET",
    "path": "/api/v1/projects/{id}/locales",
    "summary": "List locales",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "pages",
    "method": "GET",
    "path": "/api/v1/projects/{id}/pages",
    "summary": "List pages",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "pull",
    "method": "GET",
    "path": "/api/v1/projects/{id}/pull",
    "summary": "The CI endpoint.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "draft",
      "kind": "string",
      "required": false
     },
     {
      "name": "pseudo",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "releases",
    "method": "GET",
    "path": "/api/v1/projects/{id}/releases",
    "summary": "List releases",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "locale",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "releases-diff",
    "method": "GET",
    "path": "/api/v1/projects/releases/{a}/diff/{b}",
    "summary": "Key-level diff between two releases.",
    "pathParams": [
     "a",
     "b"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "review-queue",
    "method": "GET",
    "path": "/api/v1/projects/{id}/review-queue",
    "summary": "Everything machine-produced or flagged, with the key context the reviewer needs, oldest first.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "locale",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "set-keys",
    "method": "PUT",
    "path": "/api/v1/projects/{id}/keys",
    "summary": "The extract/push endpoint.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "keys",
      "kind": "array",
      "required": true
     },
     {
      "name": "prune",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "translate",
    "method": "POST",
    "path": "/api/v1/projects/{id}/translate",
    "summary": "Queue a machine first pass for a locale.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "locale",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/projects/{id}",
    "summary": "Update a project",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "siteUrl",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "update-locales",
    "method": "PATCH",
    "path": "/api/v1/projects/{id}/locales/{tag}",
    "summary": "Update a locale",
    "pathParams": [
     "id",
     "tag"
    ],
    "query": [],
    "body": [
     {
      "name": "fallback",
      "kind": "string",
      "required": false
     },
     {
      "name": "rtl",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "enabled",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "update-namespaces",
    "method": "PATCH",
    "path": "/api/v1/projects/{id}/namespaces/{name}",
    "summary": "Update a namespace",
    "pathParams": [
     "id",
     "name"
    ],
    "query": [],
    "body": [
     {
      "name": "reviewPolicy",
      "kind": "string",
      "required": true,
      "choices": [
       "standard",
       "gated"
      ]
     }
    ]
   }
  ]
 },
 {
  "area": "public",
  "routes": [
   {
    "name": "create-preview",
    "method": "POST",
    "path": "/api/v1/public/preview",
    "summary": "Create a preview",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "targetLocale",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "preview",
    "method": "GET",
    "path": "/api/v1/public/preview/{id}",
    "summary": "Poll a preview. previewId is an unguessable ULID; returns {status: 'running'|'done'|'failed', pairs?} and finalizes the job row on the first terminal poll.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "projects-catalog",
    "method": "GET",
    "path": "/api/v1/public/projects/{id}/catalog",
    "summary": "What locavello.js consumes.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "locale",
      "kind": "string",
      "required": true
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "tm",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/tm",
    "summary": "Browse the whole memory, newest-first, cursor-paged.",
    "pathParams": [],
    "query": [
     {
      "name": "target",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "search",
    "method": "GET",
    "path": "/api/v1/tm/search",
    "summary": "The TM screen's cross-project search.",
    "pathParams": [],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": true
     },
     {
      "name": "target",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "suggest",
    "method": "GET",
    "path": "/api/v1/tm/suggest",
    "summary": "Workbench + agent suggestions.",
    "pathParams": [],
    "query": [
     {
      "name": "target",
      "kind": "string",
      "required": true
     },
     {
      "name": "text",
      "kind": "string",
      "required": true
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "translations",
  "routes": [
   {
    "name": "approve",
    "method": "POST",
    "path": "/api/v1/translations/{id}/approve",
    "summary": "Approve a translation",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "reject",
    "method": "POST",
    "path": "/api/v1/translations/{id}/reject",
    "summary": "Reject a translation",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "reason",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "webhook-subscriptions",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/webhook-subscriptions",
    "summary": "Add an endpoint.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/webhook-subscriptions/{id}",
    "summary": "Delete a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "deliveries",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/deliveries",
    "summary": "List webhook deliveries.",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "subscriptionId",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "pending",
       "succeeded",
       "failed"
      ]
     },
     {
      "name": "type",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "deliveries-retry",
    "method": "POST",
    "path": "/api/v1/webhook-subscriptions/deliveries/{id}/retry",
    "summary": "Retry a webhook delivery.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "event-types",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/event-types",
    "summary": "The event types a subscription can name: every locavello.*.v1 type Locavello sends, with what it means.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "get-deliveries",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/deliveries/{id}",
    "summary": "Get a webhook delivery, with every attempt made at it.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions",
    "summary": "List webhook subscriptions",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/webhook-subscriptions/{id}",
    "summary": "Update an endpoint. `active: false` pauses it (its queued deliveries become failed); `active: true` re-enables it — also after Locavello switched it off for failing — and clears its failure streak.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     }
    ]
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      for (const name of [route.name, ...(route.aliases ?? [])]) {
      const cmd = new Command(name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd, { hidden: name !== route.name });
      }
    }
    api.addCommand(group);
  }
  return api;
}
