"""Every Locavello feature route, one method each — generated by apigen from
backend/openapi.json. Do not edit by hand; regenerate after the API changes.

Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the
client's own ``_apigen_request`` (its sign-in and response envelope).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class GeneratedApi:
    """All 47 feature routes of the Locavello API."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, body=body)

    def api_keys_create(self, *, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Mint `lv_live_…`. (POST /api/v1/api-keys).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if "name" not in payload:
            raise ValueError("api_keys_create needs name")
        return self._call("POST", f"/api/v1/api-keys", {}, payload)

    def api_keys_delete(self, id_: str) -> Any:
        """Delete an api key (DELETE /api/v1/api-keys/{id})."""
        return self._call("DELETE", f"/api/v1/api-keys/{_q(id_)}", {}, None)

    def api_keys_list(self) -> Any:
        """List api keys (GET /api/v1/api-keys)."""
        return self._call("GET", f"/api/v1/api-keys", {}, None)

    def audit_list(self, *, action: Optional[Any] = None, actor: Optional[Any] = None, q: Optional[Any] = None) -> Any:
        """List audit (GET /api/v1/audit)."""
        return self._call("GET", f"/api/v1/audit", {"action": action, "actor": actor, "q": q}, None)

    def billing_checkout(self, *, tier: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a checkout (POST /api/v1/billing/checkout).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        tier: one of free, starter, pro, scale"""
        payload: Dict[str, Any] = dict(json_body or {})
        if tier is not None:
            payload["tier"] = tier
        if "tier" not in payload:
            raise ValueError("billing_checkout needs tier")
        return self._call("POST", f"/api/v1/billing/checkout", {}, payload)

    def billing_list(self) -> Any:
        """List billing (GET /api/v1/billing)."""
        return self._call("GET", f"/api/v1/billing", {}, None)

    def glossary_create(self, *, term: Optional[str] = None, project_id: Optional[str] = None, locale: Optional[str] = None, translation: Optional[str] = None, note: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a glossary (POST /api/v1/glossary).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if term is not None:
            payload["term"] = term
        if project_id is not None:
            payload["projectId"] = project_id
        if locale is not None:
            payload["locale"] = locale
        if translation is not None:
            payload["translation"] = translation
        if note is not None:
            payload["note"] = note
        if "term" not in payload:
            raise ValueError("glossary_create needs term")
        return self._call("POST", f"/api/v1/glossary", {}, payload)

    def glossary_delete(self, id_: str) -> Any:
        """Delete a glossary (DELETE /api/v1/glossary/{id})."""
        return self._call("DELETE", f"/api/v1/glossary/{_q(id_)}", {}, None)

    def glossary_list(self, *, project_id: Optional[Any] = None) -> Any:
        """List glossary (GET /api/v1/glossary)."""
        return self._call("GET", f"/api/v1/glossary", {"projectId": project_id}, None)

    def glossary_update(self, id_: str, *, term: Optional[str] = None, project_id: Optional[str] = None, locale: Optional[str] = None, translation: Optional[str] = None, note: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a glossary (PATCH /api/v1/glossary/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if term is not None:
            payload["term"] = term
        if project_id is not None:
            payload["projectId"] = project_id
        if locale is not None:
            payload["locale"] = locale
        if translation is not None:
            payload["translation"] = translation
        if note is not None:
            payload["note"] = note
        return self._call("PATCH", f"/api/v1/glossary/{_q(id_)}", {}, payload)

    def keys_translations(self, key_id: str, locale: str, *, value: Optional[str] = None, status: Optional[str] = None, author: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Write a translation. (PUT /api/v1/keys/{keyId}/translations/{locale}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        status: one of machine, needs_review, approved"""
        payload: Dict[str, Any] = dict(json_body or {})
        if value is not None:
            payload["value"] = value
        if status is not None:
            payload["status"] = status
        if author is not None:
            payload["author"] = author
        if "value" not in payload:
            raise ValueError("keys_translations needs value")
        return self._call("PUT", f"/api/v1/keys/{_q(key_id)}/translations/{_q(locale)}", {}, payload)

    def keys_update(self, key_id: str, *, description: Optional[str] = None, max_length: Optional[int] = None, screenshot_url: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Context metadata edits from the workbench. (PATCH /api/v1/keys/{keyId}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if description is not None:
            payload["description"] = description
        if max_length is not None:
            payload["maxLength"] = max_length
        if screenshot_url is not None:
            payload["screenshotUrl"] = screenshot_url
        return self._call("PATCH", f"/api/v1/keys/{_q(key_id)}", {}, payload)

    def projects_check(self, id_: str) -> Any:
        """The CI gate report. (GET /api/v1/projects/{id}/check)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/check", {}, None)

    def projects_crawl(self, id_: str) -> Any:
        """Queue a Mode B crawl of the project's siteUrl. (POST /api/v1/projects/{id}/crawl)."""
        return self._call("POST", f"/api/v1/projects/{_q(id_)}/crawl", {}, None)

    def projects_create(self, *, slug: Optional[str] = None, name: Optional[str] = None, source_locale: Optional[str] = None, mode: Optional[str] = None, site_url: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a project (POST /api/v1/projects).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        mode: one of sdk, proxy"""
        payload: Dict[str, Any] = dict(json_body or {})
        if slug is not None:
            payload["slug"] = slug
        if name is not None:
            payload["name"] = name
        if source_locale is not None:
            payload["sourceLocale"] = source_locale
        if mode is not None:
            payload["mode"] = mode
        if site_url is not None:
            payload["siteUrl"] = site_url
        if "slug" not in payload:
            raise ValueError("projects_create needs slug")
        if "name" not in payload:
            raise ValueError("projects_create needs name")
        return self._call("POST", f"/api/v1/projects", {}, payload)

    def projects_create_locales(self, id_: str, *, tag: Optional[str] = None, fallback: Optional[str] = None, rtl: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Locales a project (POST /api/v1/projects/{id}/locales).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if tag is not None:
            payload["tag"] = tag
        if fallback is not None:
            payload["fallback"] = fallback
        if rtl is not None:
            payload["rtl"] = rtl
        if "tag" not in payload:
            raise ValueError("projects_create_locales needs tag")
        return self._call("POST", f"/api/v1/projects/{_q(id_)}/locales", {}, payload)

    def projects_create_namespaces(self, id_: str, *, name: Optional[str] = None, review_policy: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Namespaces a project (POST /api/v1/projects/{id}/namespaces).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        review_policy: one of standard, gated"""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if review_policy is not None:
            payload["reviewPolicy"] = review_policy
        if "name" not in payload:
            raise ValueError("projects_create_namespaces needs name")
        return self._call("POST", f"/api/v1/projects/{_q(id_)}/namespaces", {}, payload)

    def projects_create_releases(self, id_: str, *, locale: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Publish. (POST /api/v1/projects/{id}/releases).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if locale is not None:
            payload["locale"] = locale
        if "locale" not in payload:
            raise ValueError("projects_create_releases needs locale")
        return self._call("POST", f"/api/v1/projects/{_q(id_)}/releases", {}, payload)

    def projects_get(self, id_: str) -> Any:
        """Get a project (GET /api/v1/projects/{id})."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}", {}, None)

    def projects_jobs(self, id_: str) -> Any:
        """List jobs (GET /api/v1/projects/{id}/jobs)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/jobs", {}, None)

    def projects_jobs_2(self, job_id: str) -> Any:
        """Get a job (GET /api/v1/projects/jobs/{jobId})."""
        return self._call("GET", f"/api/v1/projects/jobs/{_q(job_id)}", {}, None)

    def projects_keys(self, id_: str, *, archived: Optional[Any] = None, locale: Optional[Any] = None, namespace: Optional[Any] = None, q: Optional[Any] = None, status: Optional[Any] = None) -> Any:
        """The workbench list. (GET /api/v1/projects/{id}/keys)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/keys", {"archived": archived, "locale": locale, "namespace": namespace, "q": q, "status": status}, None)

    def projects_list(self) -> Any:
        """List projects (GET /api/v1/projects)."""
        return self._call("GET", f"/api/v1/projects", {}, None)

    def projects_locales(self, id_: str) -> Any:
        """List locales (GET /api/v1/projects/{id}/locales)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/locales", {}, None)

    def projects_pages(self, id_: str) -> Any:
        """List pages (GET /api/v1/projects/{id}/pages)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/pages", {}, None)

    def projects_pull(self, id_: str, *, draft: Optional[Any] = None, pseudo: Optional[Any] = None) -> Any:
        """The CI endpoint. (GET /api/v1/projects/{id}/pull)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/pull", {"draft": draft, "pseudo": pseudo}, None)

    def projects_releases(self, id_: str, *, locale: Optional[Any] = None) -> Any:
        """List releases (GET /api/v1/projects/{id}/releases)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/releases", {"locale": locale}, None)

    def projects_releases_2(self, release_id: str) -> Any:
        """The frozen catalog (Mode B serving + diffs read this). (GET /api/v1/projects/releases/{releaseId})."""
        return self._call("GET", f"/api/v1/projects/releases/{_q(release_id)}", {}, None)

    def projects_releases_diff(self, a: str, b: str) -> Any:
        """Key-level diff between two releases. (GET /api/v1/projects/releases/{a}/diff/{b})."""
        return self._call("GET", f"/api/v1/projects/releases/{_q(a)}/diff/{_q(b)}", {}, None)

    def projects_review_queue(self, id_: str, *, locale: Optional[Any] = None) -> Any:
        """Everything machine-produced or flagged, with the key context the reviewer needs, oldest first. (GET /api/v1/projects/{id}/review-queue)."""
        return self._call("GET", f"/api/v1/projects/{_q(id_)}/review-queue", {"locale": locale}, None)

    def projects_set_keys(self, id_: str, *, keys: Optional[List[Any]] = None, prune: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """The extract/push endpoint. (PUT /api/v1/projects/{id}/keys).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if keys is not None:
            payload["keys"] = keys
        if prune is not None:
            payload["prune"] = prune
        if "keys" not in payload:
            raise ValueError("projects_set_keys needs keys")
        return self._call("PUT", f"/api/v1/projects/{_q(id_)}/keys", {}, payload)

    def projects_translate(self, id_: str, *, locale: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Queue a machine first pass for a locale. (POST /api/v1/projects/{id}/translate).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if locale is not None:
            payload["locale"] = locale
        if "locale" not in payload:
            raise ValueError("projects_translate needs locale")
        return self._call("POST", f"/api/v1/projects/{_q(id_)}/translate", {}, payload)

    def projects_update(self, id_: str, *, name: Optional[str] = None, site_url: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a project (PATCH /api/v1/projects/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if site_url is not None:
            payload["siteUrl"] = site_url
        return self._call("PATCH", f"/api/v1/projects/{_q(id_)}", {}, payload)

    def projects_update_locales(self, id_: str, tag: str, *, fallback: Optional[str] = None, rtl: Optional[bool] = None, enabled: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a locale (PATCH /api/v1/projects/{id}/locales/{tag}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if fallback is not None:
            payload["fallback"] = fallback
        if rtl is not None:
            payload["rtl"] = rtl
        if enabled is not None:
            payload["enabled"] = enabled
        return self._call("PATCH", f"/api/v1/projects/{_q(id_)}/locales/{_q(tag)}", {}, payload)

    def projects_update_namespaces(self, id_: str, name: str, *, review_policy: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a namespace (PATCH /api/v1/projects/{id}/namespaces/{name}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        review_policy: one of standard, gated"""
        payload: Dict[str, Any] = dict(json_body or {})
        if review_policy is not None:
            payload["reviewPolicy"] = review_policy
        if "reviewPolicy" not in payload:
            raise ValueError("projects_update_namespaces needs review_policy")
        return self._call("PATCH", f"/api/v1/projects/{_q(id_)}/namespaces/{_q(name)}", {}, payload)

    def public_create_preview(self, *, url: Optional[str] = None, target_locale: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a preview (POST /api/v1/public/preview).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if target_locale is not None:
            payload["targetLocale"] = target_locale
        if "url" not in payload:
            raise ValueError("public_create_preview needs url")
        return self._call("POST", f"/api/v1/public/preview", {}, payload)

    def public_preview(self, id_: str) -> Any:
        """Poll a preview. previewId is an unguessable ULID; returns {status: 'running'|'done'|'failed', pairs?} and finalizes the job row on the first terminal poll. (GET /api/v1/public/preview/{id})."""
        return self._call("GET", f"/api/v1/public/preview/{_q(id_)}", {}, None)

    def public_projects_catalog(self, id_: str, *, locale: Optional[Any] = None) -> Any:
        """What locavello.js consumes. (GET /api/v1/public/projects/{id}/catalog)."""
        return self._call("GET", f"/api/v1/public/projects/{_q(id_)}/catalog", {"locale": locale}, None)

    def tm_list(self, *, target: Optional[Any] = None) -> Any:
        """Browse the whole memory, newest-first, cursor-paged. (GET /api/v1/tm)."""
        return self._call("GET", f"/api/v1/tm", {"target": target}, None)

    def tm_search(self, *, q: Optional[Any] = None, target: Optional[Any] = None) -> Any:
        """The TM screen's cross-project search. (GET /api/v1/tm/search)."""
        return self._call("GET", f"/api/v1/tm/search", {"q": q, "target": target}, None)

    def tm_suggest(self, *, target: Optional[Any] = None, text: Optional[Any] = None) -> Any:
        """Workbench + agent suggestions. (GET /api/v1/tm/suggest)."""
        return self._call("GET", f"/api/v1/tm/suggest", {"target": target, "text": text}, None)

    def translations_approve(self, id_: str) -> Any:
        """Approve a translation (POST /api/v1/translations/{id}/approve)."""
        return self._call("POST", f"/api/v1/translations/{_q(id_)}/approve", {}, None)

    def translations_reject(self, id_: str, *, reason: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Reject a translation (POST /api/v1/translations/{id}/reject).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if reason is not None:
            payload["reason"] = reason
        if "reason" not in payload:
            raise ValueError("translations_reject needs reason")
        return self._call("POST", f"/api/v1/translations/{_q(id_)}/reject", {}, payload)

    def webhook_subscriptions_create(self, *, url: Optional[str] = None, events: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a webhook subscription (POST /api/v1/webhook-subscriptions).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if "url" not in payload:
            raise ValueError("webhook_subscriptions_create needs url")
        return self._call("POST", f"/api/v1/webhook-subscriptions", {}, payload)

    def webhook_subscriptions_delete(self, id_: str) -> Any:
        """Delete a webhook subscription (DELETE /api/v1/webhook-subscriptions/{id})."""
        return self._call("DELETE", f"/api/v1/webhook-subscriptions/{_q(id_)}", {}, None)

    def webhook_subscriptions_list(self) -> Any:
        """List webhook subscriptions (GET /api/v1/webhook-subscriptions)."""
        return self._call("GET", f"/api/v1/webhook-subscriptions", {}, None)

    def webhook_subscriptions_update(self, id_: str, *, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a webhook subscription (PATCH /api/v1/webhook-subscriptions/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if active is not None:
            payload["active"] = active
        if "active" not in payload:
            raise ValueError("webhook_subscriptions_update needs active")
        return self._call("PATCH", f"/api/v1/webhook-subscriptions/{_q(id_)}", {}, payload)


def _q(value: Any) -> str:
    from urllib.parse import quote

    return quote(str(value), safe="")
