// Code generated by apigen from backend/openapi.json. DO NOT EDIT.

package locavello

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// apigenTransport is the call behind every GeneratedAPI method: the SDK client sends it
// with its own sign-in and unwraps its own response envelope (a few hand-written lines
// in the client, apigenRequest). query is nil or the query string; body is nil (no body)
// or the JSON body. It returns the envelope's data, as JSON.
type apigenTransport interface {
	apigenRequest(ctx context.Context, method, path string, query url.Values, body map[string]any) (json.RawMessage, error)
}

// GeneratedAPI has all 47 feature routes of the Locavello API, one method each
// (generated from the API spec). A method takes the path parameters, then an *<Method>Args
// with the query fields (tagged query) and the JSON body fields (tagged json): required
// fields are plain values, optional ones pointers, slices or maps that nil leaves out,
// and Body passes the whole body. Each returns the response's data as JSON.
type GeneratedAPI struct{ c apigenTransport }

// Ptr returns a pointer to v, for the optional fields of the *Args structs.
func Ptr[T any](v T) *T { return &v }

// APIKeysCreateArgs are the inputs of GeneratedAPI.APIKeysCreate.
type APIKeysCreateArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// APIKeysCreate calls POST /api/v1/api-keys: Mint `lv_live_…`.
func (a *GeneratedAPI) APIKeysCreate(ctx context.Context, p *APIKeysCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &APIKeysCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("APIKeysCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/api-keys", nil, payload)
}

// APIKeysDelete calls DELETE /api/v1/api-keys/{id}: Delete an api key.
func (a *GeneratedAPI) APIKeysDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/api-keys/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// APIKeysList calls GET /api/v1/api-keys: List api keys.
func (a *GeneratedAPI) APIKeysList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/api-keys", nil, nil)
}

// AuditListArgs are the inputs of GeneratedAPI.AuditList.
type AuditListArgs struct {
	// Action is "action" in the query.
	Action any `query:"action"`

	// Actor is "actor" in the query.
	Actor any `query:"actor"`

	// Q is "q" in the query.
	Q any `query:"q"`
}

// AuditList calls GET /api/v1/audit: List audit.
func (a *GeneratedAPI) AuditList(ctx context.Context, p *AuditListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AuditListArgs{}
	}
	q := url.Values{}
	if p.Action != nil {
		q.Set("action", apigenQueryValue(p.Action))
	}
	if p.Actor != nil {
		q.Set("actor", apigenQueryValue(p.Actor))
	}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(p.Q))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/audit", q, nil)
}

// BillingCheckoutArgs are the inputs of GeneratedAPI.BillingCheckout.
type BillingCheckoutArgs struct {
	// Tier is "tier" in the body, required. One of: free, starter, pro, scale.
	Tier string `json:"tier"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// BillingCheckout calls POST /api/v1/billing/checkout: Create a checkout.
func (a *GeneratedAPI) BillingCheckout(ctx context.Context, p *BillingCheckoutArgs) (json.RawMessage, error) {
	if p == nil {
		p = &BillingCheckoutArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Tier != "" {
		payload["tier"] = p.Tier
	}
	if _, ok := payload["tier"]; !ok {
		return nil, apigenMissing("BillingCheckout", "Tier")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/billing/checkout", nil, payload)
}

// BillingList calls GET /api/v1/billing: List billing.
func (a *GeneratedAPI) BillingList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing", nil, nil)
}

// GlossaryCreateArgs are the inputs of GeneratedAPI.GlossaryCreate.
type GlossaryCreateArgs struct {
	// Term is "term" in the body, required.
	Term string `json:"term"`

	// ProjectID is "projectId" in the body.
	ProjectID *string `json:"projectId,omitempty"`

	// Locale is "locale" in the body.
	Locale *string `json:"locale,omitempty"`

	// Translation is "translation" in the body.
	Translation *string `json:"translation,omitempty"`

	// Note is "note" in the body.
	Note *string `json:"note,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// GlossaryCreate calls POST /api/v1/glossary: Create a glossary.
func (a *GeneratedAPI) GlossaryCreate(ctx context.Context, p *GlossaryCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &GlossaryCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Term != "" {
		payload["term"] = p.Term
	}
	if p.ProjectID != nil {
		payload["projectId"] = *p.ProjectID
	}
	if p.Locale != nil {
		payload["locale"] = *p.Locale
	}
	if p.Translation != nil {
		payload["translation"] = *p.Translation
	}
	if p.Note != nil {
		payload["note"] = *p.Note
	}
	if _, ok := payload["term"]; !ok {
		return nil, apigenMissing("GlossaryCreate", "Term")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/glossary", nil, payload)
}

// GlossaryDelete calls DELETE /api/v1/glossary/{id}: Delete a glossary.
func (a *GeneratedAPI) GlossaryDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/glossary/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// GlossaryListArgs are the inputs of GeneratedAPI.GlossaryList.
type GlossaryListArgs struct {
	// ProjectID is "projectId" in the query.
	ProjectID any `query:"projectId"`
}

// GlossaryList calls GET /api/v1/glossary: List glossary.
func (a *GeneratedAPI) GlossaryList(ctx context.Context, p *GlossaryListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &GlossaryListArgs{}
	}
	q := url.Values{}
	if p.ProjectID != nil {
		q.Set("projectId", apigenQueryValue(p.ProjectID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/glossary", q, nil)
}

// GlossaryUpdateArgs are the inputs of GeneratedAPI.GlossaryUpdate.
type GlossaryUpdateArgs struct {
	// Term is "term" in the body.
	Term *string `json:"term,omitempty"`

	// ProjectID is "projectId" in the body.
	ProjectID *string `json:"projectId,omitempty"`

	// Locale is "locale" in the body.
	Locale *string `json:"locale,omitempty"`

	// Translation is "translation" in the body.
	Translation *string `json:"translation,omitempty"`

	// Note is "note" in the body.
	Note *string `json:"note,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// GlossaryUpdate calls PATCH /api/v1/glossary/{id}: Update a glossary.
func (a *GeneratedAPI) GlossaryUpdate(ctx context.Context, id string, p *GlossaryUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &GlossaryUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Term != nil {
		payload["term"] = *p.Term
	}
	if p.ProjectID != nil {
		payload["projectId"] = *p.ProjectID
	}
	if p.Locale != nil {
		payload["locale"] = *p.Locale
	}
	if p.Translation != nil {
		payload["translation"] = *p.Translation
	}
	if p.Note != nil {
		payload["note"] = *p.Note
	}
	path := "/api/v1/glossary/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// KeysTranslationsArgs are the inputs of GeneratedAPI.KeysTranslations.
type KeysTranslationsArgs struct {
	// Value is "value" in the body, required.
	Value string `json:"value"`

	// Status is "status" in the body. One of: machine, needs_review, approved.
	Status *string `json:"status,omitempty"`

	// Author is "author" in the body.
	Author *string `json:"author,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// KeysTranslations calls PUT /api/v1/keys/{keyId}/translations/{locale}: Write a translation.
func (a *GeneratedAPI) KeysTranslations(ctx context.Context, keyID string, locale string, p *KeysTranslationsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &KeysTranslationsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Value != "" {
		payload["value"] = p.Value
	}
	if p.Status != nil {
		payload["status"] = *p.Status
	}
	if p.Author != nil {
		payload["author"] = *p.Author
	}
	if _, ok := payload["value"]; !ok {
		return nil, apigenMissing("KeysTranslations", "Value")
	}
	path := "/api/v1/keys/" + url.PathEscape(keyID) + "/translations/" + url.PathEscape(locale)
	return a.c.apigenRequest(ctx, "PUT", path, nil, payload)
}

// KeysUpdateArgs are the inputs of GeneratedAPI.KeysUpdate.
type KeysUpdateArgs struct {
	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// MaxLength is "maxLength" in the body.
	MaxLength *int `json:"maxLength,omitempty"`

	// ScreenshotURL is "screenshotUrl" in the body.
	ScreenshotURL *string `json:"screenshotUrl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// KeysUpdate calls PATCH /api/v1/keys/{keyId}: Context metadata edits from the workbench.
func (a *GeneratedAPI) KeysUpdate(ctx context.Context, keyID string, p *KeysUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &KeysUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.MaxLength != nil {
		payload["maxLength"] = *p.MaxLength
	}
	if p.ScreenshotURL != nil {
		payload["screenshotUrl"] = *p.ScreenshotURL
	}
	path := "/api/v1/keys/" + url.PathEscape(keyID)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ProjectsCheck calls GET /api/v1/projects/{id}/check: The CI gate report.
func (a *GeneratedAPI) ProjectsCheck(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/check"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsCrawl calls POST /api/v1/projects/{id}/crawl: Queue a Mode B crawl of the project's siteUrl.
func (a *GeneratedAPI) ProjectsCrawl(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/crawl"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// ProjectsCreateArgs are the inputs of GeneratedAPI.ProjectsCreate.
type ProjectsCreateArgs struct {
	// Slug is "slug" in the body, required.
	Slug string `json:"slug"`

	// Name is "name" in the body, required.
	Name string `json:"name"`

	// SourceLocale is "sourceLocale" in the body.
	SourceLocale *string `json:"sourceLocale,omitempty"`

	// Mode is "mode" in the body. One of: sdk, proxy.
	Mode *string `json:"mode,omitempty"`

	// SiteURL is "siteUrl" in the body.
	SiteURL *string `json:"siteUrl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreate calls POST /api/v1/projects: Create a project.
func (a *GeneratedAPI) ProjectsCreate(ctx context.Context, p *ProjectsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Slug != "" {
		payload["slug"] = p.Slug
	}
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.SourceLocale != nil {
		payload["sourceLocale"] = *p.SourceLocale
	}
	if p.Mode != nil {
		payload["mode"] = *p.Mode
	}
	if p.SiteURL != nil {
		payload["siteUrl"] = *p.SiteURL
	}
	if _, ok := payload["slug"]; !ok {
		return nil, apigenMissing("ProjectsCreate", "Slug")
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("ProjectsCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/projects", nil, payload)
}

// ProjectsCreateLocalesArgs are the inputs of GeneratedAPI.ProjectsCreateLocales.
type ProjectsCreateLocalesArgs struct {
	// Tag is "tag" in the body, required.
	Tag string `json:"tag"`

	// Fallback is "fallback" in the body.
	Fallback *string `json:"fallback,omitempty"`

	// Rtl is "rtl" in the body.
	Rtl *bool `json:"rtl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreateLocales calls POST /api/v1/projects/{id}/locales: Locales a project.
func (a *GeneratedAPI) ProjectsCreateLocales(ctx context.Context, id string, p *ProjectsCreateLocalesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateLocalesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Tag != "" {
		payload["tag"] = p.Tag
	}
	if p.Fallback != nil {
		payload["fallback"] = *p.Fallback
	}
	if p.Rtl != nil {
		payload["rtl"] = *p.Rtl
	}
	if _, ok := payload["tag"]; !ok {
		return nil, apigenMissing("ProjectsCreateLocales", "Tag")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/locales"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsCreateNamespacesArgs are the inputs of GeneratedAPI.ProjectsCreateNamespaces.
type ProjectsCreateNamespacesArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// ReviewPolicy is "reviewPolicy" in the body. One of: standard, gated.
	ReviewPolicy *string `json:"reviewPolicy,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreateNamespaces calls POST /api/v1/projects/{id}/namespaces: Namespaces a project.
func (a *GeneratedAPI) ProjectsCreateNamespaces(ctx context.Context, id string, p *ProjectsCreateNamespacesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateNamespacesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.ReviewPolicy != nil {
		payload["reviewPolicy"] = *p.ReviewPolicy
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("ProjectsCreateNamespaces", "Name")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/namespaces"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsCreateReleasesArgs are the inputs of GeneratedAPI.ProjectsCreateReleases.
type ProjectsCreateReleasesArgs struct {
	// Locale is "locale" in the body, required.
	Locale string `json:"locale"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsCreateReleases calls POST /api/v1/projects/{id}/releases: Publish.
func (a *GeneratedAPI) ProjectsCreateReleases(ctx context.Context, id string, p *ProjectsCreateReleasesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsCreateReleasesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Locale != "" {
		payload["locale"] = p.Locale
	}
	if _, ok := payload["locale"]; !ok {
		return nil, apigenMissing("ProjectsCreateReleases", "Locale")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/releases"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsGet calls GET /api/v1/projects/{id}: Get a project.
func (a *GeneratedAPI) ProjectsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsJobs calls GET /api/v1/projects/{id}/jobs: List jobs.
func (a *GeneratedAPI) ProjectsJobs(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/jobs"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsJobs2 calls GET /api/v1/projects/jobs/{jobId}: Get a job.
func (a *GeneratedAPI) ProjectsJobs2(ctx context.Context, jobID string) (json.RawMessage, error) {
	path := "/api/v1/projects/jobs/" + url.PathEscape(jobID)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsKeysArgs are the inputs of GeneratedAPI.ProjectsKeys.
type ProjectsKeysArgs struct {
	// Archived is "archived" in the query.
	Archived any `query:"archived"`

	// Locale is "locale" in the query.
	Locale any `query:"locale"`

	// Namespace is "namespace" in the query.
	Namespace any `query:"namespace"`

	// Q is "q" in the query.
	Q any `query:"q"`

	// Status is "status" in the query.
	Status any `query:"status"`
}

// ProjectsKeys calls GET /api/v1/projects/{id}/keys: The workbench list.
func (a *GeneratedAPI) ProjectsKeys(ctx context.Context, id string, p *ProjectsKeysArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsKeysArgs{}
	}
	q := url.Values{}
	if p.Archived != nil {
		q.Set("archived", apigenQueryValue(p.Archived))
	}
	if p.Locale != nil {
		q.Set("locale", apigenQueryValue(p.Locale))
	}
	if p.Namespace != nil {
		q.Set("namespace", apigenQueryValue(p.Namespace))
	}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(p.Q))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(p.Status))
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/keys"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ProjectsList calls GET /api/v1/projects: List projects.
func (a *GeneratedAPI) ProjectsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/projects", nil, nil)
}

// ProjectsLocales calls GET /api/v1/projects/{id}/locales: List locales.
func (a *GeneratedAPI) ProjectsLocales(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/locales"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsPages calls GET /api/v1/projects/{id}/pages: List pages.
func (a *GeneratedAPI) ProjectsPages(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pages"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsPullArgs are the inputs of GeneratedAPI.ProjectsPull.
type ProjectsPullArgs struct {
	// Draft is "draft" in the query.
	Draft any `query:"draft"`

	// Pseudo is "pseudo" in the query.
	Pseudo any `query:"pseudo"`
}

// ProjectsPull calls GET /api/v1/projects/{id}/pull: The CI endpoint.
func (a *GeneratedAPI) ProjectsPull(ctx context.Context, id string, p *ProjectsPullArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsPullArgs{}
	}
	q := url.Values{}
	if p.Draft != nil {
		q.Set("draft", apigenQueryValue(p.Draft))
	}
	if p.Pseudo != nil {
		q.Set("pseudo", apigenQueryValue(p.Pseudo))
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/pull"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ProjectsReleasesArgs are the inputs of GeneratedAPI.ProjectsReleases.
type ProjectsReleasesArgs struct {
	// Locale is "locale" in the query.
	Locale any `query:"locale"`
}

// ProjectsReleases calls GET /api/v1/projects/{id}/releases: List releases.
func (a *GeneratedAPI) ProjectsReleases(ctx context.Context, id string, p *ProjectsReleasesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsReleasesArgs{}
	}
	q := url.Values{}
	if p.Locale != nil {
		q.Set("locale", apigenQueryValue(p.Locale))
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/releases"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ProjectsReleases2 calls GET /api/v1/projects/releases/{releaseId}: The frozen catalog (Mode B serving + diffs read this).
func (a *GeneratedAPI) ProjectsReleases2(ctx context.Context, releaseID string) (json.RawMessage, error) {
	path := "/api/v1/projects/releases/" + url.PathEscape(releaseID)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsReleasesDiff calls GET /api/v1/projects/releases/{a}/diff/{b}: Key-level diff between two releases.
func (a *GeneratedAPI) ProjectsReleasesDiff(ctx context.Context, aArg string, b string) (json.RawMessage, error) {
	path := "/api/v1/projects/releases/" + url.PathEscape(aArg) + "/diff/" + url.PathEscape(b)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProjectsReviewQueueArgs are the inputs of GeneratedAPI.ProjectsReviewQueue.
type ProjectsReviewQueueArgs struct {
	// Locale is "locale" in the query.
	Locale any `query:"locale"`
}

// ProjectsReviewQueue calls GET /api/v1/projects/{id}/review-queue: Everything machine-produced or flagged, with the key context the reviewer needs, oldest first.
func (a *GeneratedAPI) ProjectsReviewQueue(ctx context.Context, id string, p *ProjectsReviewQueueArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsReviewQueueArgs{}
	}
	q := url.Values{}
	if p.Locale != nil {
		q.Set("locale", apigenQueryValue(p.Locale))
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/review-queue"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ProjectsSetKeysArgs are the inputs of GeneratedAPI.ProjectsSetKeys.
type ProjectsSetKeysArgs struct {
	// Keys is "keys" in the body, required.
	Keys []any `json:"keys"`

	// Prune is "prune" in the body.
	Prune *bool `json:"prune,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsSetKeys calls PUT /api/v1/projects/{id}/keys: The extract/push endpoint.
func (a *GeneratedAPI) ProjectsSetKeys(ctx context.Context, id string, p *ProjectsSetKeysArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsSetKeysArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Keys != nil {
		payload["keys"] = p.Keys
	}
	if p.Prune != nil {
		payload["prune"] = *p.Prune
	}
	if _, ok := payload["keys"]; !ok {
		return nil, apigenMissing("ProjectsSetKeys", "Keys")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/keys"
	return a.c.apigenRequest(ctx, "PUT", path, nil, payload)
}

// ProjectsTranslateArgs are the inputs of GeneratedAPI.ProjectsTranslate.
type ProjectsTranslateArgs struct {
	// Locale is "locale" in the body, required.
	Locale string `json:"locale"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsTranslate calls POST /api/v1/projects/{id}/translate: Queue a machine first pass for a locale.
func (a *GeneratedAPI) ProjectsTranslate(ctx context.Context, id string, p *ProjectsTranslateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsTranslateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Locale != "" {
		payload["locale"] = p.Locale
	}
	if _, ok := payload["locale"]; !ok {
		return nil, apigenMissing("ProjectsTranslate", "Locale")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/translate"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProjectsUpdateArgs are the inputs of GeneratedAPI.ProjectsUpdate.
type ProjectsUpdateArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// SiteURL is "siteUrl" in the body.
	SiteURL *string `json:"siteUrl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsUpdate calls PATCH /api/v1/projects/{id}: Update a project.
func (a *GeneratedAPI) ProjectsUpdate(ctx context.Context, id string, p *ProjectsUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.SiteURL != nil {
		payload["siteUrl"] = *p.SiteURL
	}
	path := "/api/v1/projects/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ProjectsUpdateLocalesArgs are the inputs of GeneratedAPI.ProjectsUpdateLocales.
type ProjectsUpdateLocalesArgs struct {
	// Fallback is "fallback" in the body.
	Fallback *string `json:"fallback,omitempty"`

	// Rtl is "rtl" in the body.
	Rtl *bool `json:"rtl,omitempty"`

	// Enabled is "enabled" in the body.
	Enabled *bool `json:"enabled,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsUpdateLocales calls PATCH /api/v1/projects/{id}/locales/{tag}: Update a locale.
func (a *GeneratedAPI) ProjectsUpdateLocales(ctx context.Context, id string, tag string, p *ProjectsUpdateLocalesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsUpdateLocalesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Fallback != nil {
		payload["fallback"] = *p.Fallback
	}
	if p.Rtl != nil {
		payload["rtl"] = *p.Rtl
	}
	if p.Enabled != nil {
		payload["enabled"] = *p.Enabled
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/locales/" + url.PathEscape(tag)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ProjectsUpdateNamespacesArgs are the inputs of GeneratedAPI.ProjectsUpdateNamespaces.
type ProjectsUpdateNamespacesArgs struct {
	// ReviewPolicy is "reviewPolicy" in the body, required. One of: standard, gated.
	ReviewPolicy string `json:"reviewPolicy"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProjectsUpdateNamespaces calls PATCH /api/v1/projects/{id}/namespaces/{name}: Update a namespace.
func (a *GeneratedAPI) ProjectsUpdateNamespaces(ctx context.Context, id string, name string, p *ProjectsUpdateNamespacesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProjectsUpdateNamespacesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ReviewPolicy != "" {
		payload["reviewPolicy"] = p.ReviewPolicy
	}
	if _, ok := payload["reviewPolicy"]; !ok {
		return nil, apigenMissing("ProjectsUpdateNamespaces", "ReviewPolicy")
	}
	path := "/api/v1/projects/" + url.PathEscape(id) + "/namespaces/" + url.PathEscape(name)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// PublicCreatePreviewArgs are the inputs of GeneratedAPI.PublicCreatePreview.
type PublicCreatePreviewArgs struct {
	// URL is "url" in the body, required.
	URL string `json:"url"`

	// TargetLocale is "targetLocale" in the body.
	TargetLocale *string `json:"targetLocale,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// PublicCreatePreview calls POST /api/v1/public/preview: Create a preview.
func (a *GeneratedAPI) PublicCreatePreview(ctx context.Context, p *PublicCreatePreviewArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicCreatePreviewArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != "" {
		payload["url"] = p.URL
	}
	if p.TargetLocale != nil {
		payload["targetLocale"] = *p.TargetLocale
	}
	if _, ok := payload["url"]; !ok {
		return nil, apigenMissing("PublicCreatePreview", "URL")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/public/preview", nil, payload)
}

// PublicPreview calls GET /api/v1/public/preview/{id}: Poll a preview. previewId is an unguessable ULID; returns {status: 'running'|'done'|'failed', pairs?} and finalizes the job row on the first terminal poll.
func (a *GeneratedAPI) PublicPreview(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/public/preview/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// PublicProjectsCatalogArgs are the inputs of GeneratedAPI.PublicProjectsCatalog.
type PublicProjectsCatalogArgs struct {
	// Locale is "locale" in the query.
	Locale any `query:"locale"`
}

// PublicProjectsCatalog calls GET /api/v1/public/projects/{id}/catalog: What locavello.js consumes.
func (a *GeneratedAPI) PublicProjectsCatalog(ctx context.Context, id string, p *PublicProjectsCatalogArgs) (json.RawMessage, error) {
	if p == nil {
		p = &PublicProjectsCatalogArgs{}
	}
	q := url.Values{}
	if p.Locale != nil {
		q.Set("locale", apigenQueryValue(p.Locale))
	}
	path := "/api/v1/public/projects/" + url.PathEscape(id) + "/catalog"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// TmListArgs are the inputs of GeneratedAPI.TmList.
type TmListArgs struct {
	// Target is "target" in the query.
	Target any `query:"target"`
}

// TmList calls GET /api/v1/tm: Browse the whole memory, newest-first, cursor-paged.
func (a *GeneratedAPI) TmList(ctx context.Context, p *TmListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TmListArgs{}
	}
	q := url.Values{}
	if p.Target != nil {
		q.Set("target", apigenQueryValue(p.Target))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/tm", q, nil)
}

// TmSearchArgs are the inputs of GeneratedAPI.TmSearch.
type TmSearchArgs struct {
	// Q is "q" in the query.
	Q any `query:"q"`

	// Target is "target" in the query.
	Target any `query:"target"`
}

// TmSearch calls GET /api/v1/tm/search: The TM screen's cross-project search.
func (a *GeneratedAPI) TmSearch(ctx context.Context, p *TmSearchArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TmSearchArgs{}
	}
	q := url.Values{}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(p.Q))
	}
	if p.Target != nil {
		q.Set("target", apigenQueryValue(p.Target))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/tm/search", q, nil)
}

// TmSuggestArgs are the inputs of GeneratedAPI.TmSuggest.
type TmSuggestArgs struct {
	// Target is "target" in the query.
	Target any `query:"target"`

	// Text is "text" in the query.
	Text any `query:"text"`
}

// TmSuggest calls GET /api/v1/tm/suggest: Workbench + agent suggestions.
func (a *GeneratedAPI) TmSuggest(ctx context.Context, p *TmSuggestArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TmSuggestArgs{}
	}
	q := url.Values{}
	if p.Target != nil {
		q.Set("target", apigenQueryValue(p.Target))
	}
	if p.Text != nil {
		q.Set("text", apigenQueryValue(p.Text))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/tm/suggest", q, nil)
}

// TranslationsApprove calls POST /api/v1/translations/{id}/approve: Approve a translation.
func (a *GeneratedAPI) TranslationsApprove(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/translations/" + url.PathEscape(id) + "/approve"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// TranslationsRejectArgs are the inputs of GeneratedAPI.TranslationsReject.
type TranslationsRejectArgs struct {
	// Reason is "reason" in the body, required.
	Reason string `json:"reason"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// TranslationsReject calls POST /api/v1/translations/{id}/reject: Reject a translation.
func (a *GeneratedAPI) TranslationsReject(ctx context.Context, id string, p *TranslationsRejectArgs) (json.RawMessage, error) {
	if p == nil {
		p = &TranslationsRejectArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Reason != "" {
		payload["reason"] = p.Reason
	}
	if _, ok := payload["reason"]; !ok {
		return nil, apigenMissing("TranslationsReject", "Reason")
	}
	path := "/api/v1/translations/" + url.PathEscape(id) + "/reject"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// WebhookSubscriptionsCreateArgs are the inputs of GeneratedAPI.WebhookSubscriptionsCreate.
type WebhookSubscriptionsCreateArgs struct {
	// URL is "url" in the body, required.
	URL string `json:"url"`

	// Events is "events" in the body.
	Events []string `json:"events,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WebhookSubscriptionsCreate calls POST /api/v1/webhook-subscriptions: Create a webhook subscription.
func (a *GeneratedAPI) WebhookSubscriptionsCreate(ctx context.Context, p *WebhookSubscriptionsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhookSubscriptionsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != "" {
		payload["url"] = p.URL
	}
	if p.Events != nil {
		payload["events"] = p.Events
	}
	if _, ok := payload["url"]; !ok {
		return nil, apigenMissing("WebhookSubscriptionsCreate", "URL")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/webhook-subscriptions", nil, payload)
}

// WebhookSubscriptionsDelete calls DELETE /api/v1/webhook-subscriptions/{id}: Delete a webhook subscription.
func (a *GeneratedAPI) WebhookSubscriptionsDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// WebhookSubscriptionsList calls GET /api/v1/webhook-subscriptions: List webhook subscriptions.
func (a *GeneratedAPI) WebhookSubscriptionsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/webhook-subscriptions", nil, nil)
}

// WebhookSubscriptionsUpdateArgs are the inputs of GeneratedAPI.WebhookSubscriptionsUpdate.
type WebhookSubscriptionsUpdateArgs struct {
	// Active is "active" in the body, required.
	Active bool `json:"active"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WebhookSubscriptionsUpdate calls PATCH /api/v1/webhook-subscriptions/{id}: Update a webhook subscription.
func (a *GeneratedAPI) WebhookSubscriptionsUpdate(ctx context.Context, id string, p *WebhookSubscriptionsUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhookSubscriptionsUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if _, ok := payload["active"]; !ok || p.Active {
		payload["active"] = p.Active
	}
	path := "/api/v1/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// apigenBody copies Body, so the fields set over it never change the caller's map.
func apigenBody(body map[string]any) map[string]any {
	out := make(map[string]any, len(body))
	for k, v := range body {
		out[k] = v
	}
	return out
}

// apigenQueryValue writes a query value the way the server reads it: strings as they are,
// numbers and booleans as JSON writes them, anything else as JSON.
func apigenQueryValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}

// apigenMissing is the error for a required body field that was neither set nor in Body.
func apigenMissing(method, field string) error {
	return fmt.Errorf("%s needs %s (or its key in Body)", method, field)
}
