// Generated by apigen docs from backend/openapi.json — do not edit by hand.
import type { DocMeta } from './markdown';

export const REFERENCE_NAV: DocMeta[] = [
  {
    "slug": "api/reference",
    "title": "All routes",
    "group": "API reference (every route)",
    "href": "/docs/api/reference"
  },
  {
    "slug": "api/reference/api-keys",
    "title": "Api keys",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/api-keys"
  },
  {
    "slug": "api/reference/audit",
    "title": "Audit",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/audit"
  },
  {
    "slug": "api/reference/billing",
    "title": "Billing",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/billing"
  },
  {
    "slug": "api/reference/glossary",
    "title": "Glossary",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/glossary"
  },
  {
    "slug": "api/reference/keys",
    "title": "Keys",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/keys"
  },
  {
    "slug": "api/reference/projects",
    "title": "Projects",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/projects"
  },
  {
    "slug": "api/reference/public",
    "title": "Public",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/public"
  },
  {
    "slug": "api/reference/tm",
    "title": "Tm",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/tm"
  },
  {
    "slug": "api/reference/translations",
    "title": "Translations",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/translations"
  },
  {
    "slug": "api/reference/webhook-subscriptions",
    "title": "Webhook subscriptions",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/webhook-subscriptions"
  }
];
